obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE) += mmi_parallel_charger.o
mmi_parallel_charger-objs += mmi_charger_class.o
mmi_parallel_charger-objs += mmi_charger_core.o
mmi_parallel_charger-objs += mmi_charger_pump_policy.o
mmi_parallel_charger-objs += bq2597x_charger.o
mmi_parallel_charger-objs += qpnp_pmic_charger.o
