#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_CHIPONE_FPS_MMI)	+= chipone_fps_mmi/
obj-$(CONFIG_FINGERPRINT_FPC_TEE_MMI)	+= fpc_fps_mmi/

